const mongoose = require('mongoose');

const NOTIFICATION_TYPE = {
    COACH_REQUEST: "coach_request",
    ATHLETE_REQUEST: "athlete_request",
    REQUEST_SUCCESS: "request_success",
    REQUEST_REFUSE: "request_refuse",
    CANCEL_ATHLETE_TO_COACH_LINK: "cancel_athlete_to_coach_link",
    CANCEL_COACH_TO_ATHLETE_LINK: "cancel_coach_to_athlete_link",
    CANCEL_ATHLETE_TO_COACH_LINK_REQUEST: "cancel_athlete_to_coach_link_request",
    CANCEL_COACH_TO_ATHLETE_LINK_REQUEST: "cancel_coach_to_athlete_link_request",
    TRAINING_CREATED: "training_created",
    TRAINING_MODIFIED: "training_modified",
    DISMISS: "dismiss"
}

const NOTIFICATION_ONLY_DISMISS = [
    NOTIFICATION_TYPE.REQUEST_SUCCESS,
    NOTIFICATION_TYPE.REQUEST_REFUSE,
    NOTIFICATION_TYPE.CANCEL_ATHLETE_TO_COACH_LINK,
    NOTIFICATION_TYPE.CANCEL_COACH_TO_ATHLETE_LINK,
    NOTIFICATION_TYPE.CANCEL_ATHLETE_TO_COACH_LINK_REQUEST,
    NOTIFICATION_TYPE.CANCEL_COACH_TO_ATHLETE_LINK_REQUEST,
    NOTIFICATION_TYPE.TRAINING_MODIFIED,
    NOTIFICATION_TYPE.TRAINING_MODIFIED,
    NOTIFICATION_TYPE.DISMISS,
]

module.exports = {
    NOTIFICATION_TYPE: NOTIFICATION_TYPE,
    NOTIFICATION_ONLY_DISMISS: NOTIFICATION_TYPE
}